'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("LanguageScript.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 工作文件
        '''决议草案
        '''修正案
        '''指令草案.
        '''</summary>
        Friend ReadOnly Property file1() As String
            Get
                Return ResourceManager.GetString("file1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Working Paper 
        '''Draft Resolution 
        '''Amendment 
        '''Draft Directive .
        '''</summary>
        Friend ReadOnly Property file2() As String
            Get
                Return ResourceManager.GetString("file2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 备选议题1: 
        '''备选议题2: 
        '''第
        '''会期
        '''开始
        '''  
        '''欢迎参加
        '''会议将于
        '''开始，请各位代表做好准备
        '''决议草案上交截止时间 
        '''修正案上交截止时间 
        '''指令草案上交截止时间 
        '''请代表抓紧时间完成相关文件起草
        '''本次会议因故推迟至
        '''本次会议现在提前开始，请各位代表做好准备.
        '''</summary>
        Friend ReadOnly Property info1() As String
            Get
                Return ResourceManager.GetString("info1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Option 1: 
        '''Option 2: 
        '''Session 
        '''
        ''' Start
        ''', 
        '''Welcome to
        '''The session will start at 
        ''', all the delegates please get ready
        '''Deadline of handing draft resolutions is 
        '''Deadline of handing amendments is 
        '''Deadline of handing draft directives is 
        '''All the delegates please finish drafting your file in time
        '''The starting of session is delayed to 
        '''The session now start in advance, delegates please get ready.
        '''</summary>
        Friend ReadOnly Property info2() As String
            Get
                Return ResourceManager.GetString("info2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 请问台下有无附议？
        '''请支持此动议的国家高举国家牌。
        '''该动议是否获得通过？
        '''未获通过
        '''动议一个有主持核心磋商
        '''议题为
        '''总时长为
        '''分钟, 每位代表
        '''秒
        '''动议一个自由磋商
        '''分钟
        '''动议将发言时间调整为
        '''分
        '''秒
        '''动议对
        '''进行投票
        '''动议开始茶歇
        '''动议结束辩论
        '''动议休会
        '''动议
        '''获得通过，茶歇开始 (
        '''获得通过，下面将进入投票环节
        '''获得通过，第
        '''会期结束
        '''动议更改投票顺序
        '''将优先对
        '''进行投票.
        '''</summary>
        Friend ReadOnly Property motion1() As String
            Get
                Return ResourceManager.GetString("motion1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are there any second?
        '''Delegates who are in favor of this motion, please raise your placards.
        '''Does the motion pass?
        '''Motion Failed
        ''' motions for a moderated caucus
        '''Topic: 
        '''Total time: 
        ''' min, 
        ''' sec for each
        ''' motions for an unmoderated caucus
        ''' min
        ''' motions for changing speech time to
        '''m
        '''s
        ''' motions to vote for 
        ''' 
        ''' motions to start a tea-break
        ''' motions to end the debate
        ''' motions to suspend the meeting
        ''' motions 
        '''Motion passes, tea break is starting (Time: 
        '''Motion passes, voting procedure will be [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property motion2() As String
            Get
                Return ResourceManager.GetString("motion2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 出席国家数:
        '''简单多数:
        '''三分之二多数:
        '''20%:
        '''赞成:
        '''反对:
        '''弃权:
        '''中国
        '''美国
        '''英国
        '''法国
        '''俄罗斯.
        '''</summary>
        Friend ReadOnly Property present1() As String
            Get
                Return ResourceManager.GetString("present1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Presents:
        '''Simple Majority:
        '''2/3 Majority:
        '''20%:
        '''Yes:
        '''No:
        '''Abstain:
        '''China
        '''USA
        '''UK
        '''France
        '''Russia.
        '''</summary>
        Friend ReadOnly Property present2() As String
            Get
                Return ResourceManager.GetString("present2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 特吕格韦·赖伊
        '''达格·哈马舍尔德
        '''吴丹
        '''库尔特·瓦尔德海姆
        '''哈维尔·佩雷斯·德奎利亚尔
        '''布特罗斯·布特罗斯-加利
        '''科菲·安南
        '''潘基文先生
        '''NATIONS
        '''中国
        '''美国
        '''英国
        '''法国
        '''俄罗斯
        '''苏联
        '''2014
        '''乍得
        '''尼日利亚
        '''卢旺达
        '''约旦
        '''韩国
        '''智利
        '''阿根廷
        '''澳大利亚
        '''卢森堡
        '''立陶宛
        '''2013
        '''摩洛哥
        '''多哥
        '''巴基斯坦
        '''危地马拉
        '''阿塞拜疆
        '''卢旺达
        '''韩国
        '''阿根廷
        '''澳大利亚
        '''卢森堡
        '''2012
        '''阿塞拜疆
        '''危地马拉
        '''摩洛哥
        '''巴基斯坦
        '''多哥
        '''印度
        '''哥伦比亚
        '''南非
        '''德国
        '''葡萄牙
        '''2011
        '''波斯尼亚和黑塞哥维那
        '''黎巴嫩
        '''尼日利亚
        '''加蓬
        '''巴西
        '''印度
        '''哥伦比亚
        '''南非
        '''德国
        '''葡萄牙
        '''2010
        '''日本
        '''土耳其
        '''奥地利
        '''墨西哥
        '''乌干达
        '''波斯尼亚和黑塞哥维那
        '''黎巴嫩
        '''尼日利亚
        '''加蓬
        '''巴西
        '''2009
        '''利比亚
        '''越南
        '''布基纳法索
        '''克罗地亚
        '''哥斯达黎加
        '''日本
        '''土耳其
        '''奥地利
        '''墨西哥
        '''乌干达
        '''2008
        '''比利时
        '''意大利
        '''南非
        '''印度尼西亚
        '''巴拿马
        '''利比亚
        '''越南
        '''布基纳法索
        '''克罗地亚        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property scnation1() As String
            Get
                Return ResourceManager.GetString("scnation1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Trygve Lie
        '''Dag Hammarskjold
        '''U Thant
        '''Kurt Waldheim
        '''Javier Perez de Cuellar
        '''Boutros Boutros - Ghali
        '''Kofi Annan
        '''Ban Ki-moon
        '''NATIONS
        '''China
        '''USA
        '''United Kingdom
        '''France
        '''Russia
        '''USSR
        '''2014
        '''Chad
        '''Nigeria
        '''Rwanda
        '''Jordan
        '''Korea
        '''Chile
        '''Argentina
        '''Australia
        '''Luxembourg
        '''Lithuania
        '''2013
        '''Morocco
        '''Togo
        '''Pakistan
        '''Guatemala
        '''Azerbaijan
        '''Rwanda
        '''Korea
        '''Argentina
        '''Australia
        '''Luxembourg
        '''2012
        '''Azerbaijan
        '''Guatemala
        '''Morocco
        '''Pakistan
        '''Togo
        '''India
        '''Colombia
        '''South Africa
        '''Germany
        '''Portugal
        '''2011
        '''Bosnia and Herz [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property scnation2() As String
            Get
                Return ResourceManager.GetString("scnation2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 现在是本地时间
        '''，安全理事会即将召开第
        '''次会议。
        '''现收到一份来自
        '''的提请。我根据安全理事会暂行议事规则第三条召开会议。
        '''会议第一项，对议程的表决。请同意此议程的国家举手。
        '''该议程显然获得通过。
        '''议程未获通过
        '''我根据安全理事会暂行议事规则第三十七条邀请
        '''我根据安全理事会暂行议事规则第三十九条邀请
        '''出席。
        '''我欢迎
        '''出席此次会议，下面有请他发言。
        '''感谢
        '''。
        '''下面我根据安理会暂行议事规则第二十七条，邀请诸位代表发言。
        '''首先，我邀请
        '''代表发言。
        '''代表。下面我邀请
        '''现在发言名单上没有更多国家。
        '''安理会主席现收到决议草案
        '''。经审议该文件无问题，已印发全场。
        '''现对该决议草案进行表决。
        '''&lt;正在对决议草案
        '''进行表决&gt;
        '''请赞成该决议草案的国家举手。
        '''请对该决议草案弃权的国家举手。
        '''请反对该决议草案的国家举手。
        '''该决议草案获得通过，将成为第
        '''号决议。
        '''由于
        '''赞成未过九票
        '''行使否决权
        '''，该决议草案未获通过。
        '''代表
        '''议程: 
        '''本次会议将
        '''对决议草案
        '''进行表决
        '''，并
        '''邀请
        '''联合国秘书长
        '''以及
        '''下述代表
        '''发言
        '''、
        '''我现在请安理会成员进行非正式磋商，继 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property scscript1() As String
            Get
                Return ResourceManager.GetString("scscript1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 现在是本地时间
        '''，安全理事会即将召开第
        '''次会议。
        '''现收到一份来自
        '''的提请。我根据安全理事会暂行议事规则第三条召开会议。
        '''会议第一项，对议程的表决。请同意此议程的国家举手。
        '''The agenda was adopted.
        '''&lt;Agenda not adopted&gt;
        '''In accordance with rule 37 of the Council’s provisional rules of procedure, I invite 
        '''In accordance with rule 39 of the Council’s provisional rules of procedure, I invite 
        '''出席。
        '''我欢迎
        '''出席此次会议，下面有请他发言。
        '''感谢
        '''。
        '''下面我根据安理会暂行议事规则第二十七条，邀请诸位代表发言。
        '''首先，我邀请
        '''代表发言。
        '''代表。下面我邀请
        '''There are no more names inscribed on the list of speakers. 
        '''安理会主席现收到决议草案
        '''。经审议该文件无问题，已印发全场。
        '''现对该决议草案进行表决。
        '''&lt; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property scscript2() As String
            Get
                Return ResourceManager.GetString("scscript2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 议题辩论结束
        '''本轮动议结束
        '''阅读时间到
        '''文件介绍时间到
        '''发言时间到
        '''时间到，请各位代表就座
        '''剩余 
        ''' 分 
        ''' 秒
        '''发言已用去 .
        '''</summary>
        Friend ReadOnly Property timer1() As String
            Get
                Return ResourceManager.GetString("timer1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Topic Debate Ended
        '''Motion Ended
        '''Reading Time Over
        '''Introduction Time Over
        '''Speech Time Over
        '''Time over, all the delegates please be seat
        '''Time remaining:
        '''m
        '''s
        '''Time used:.
        '''</summary>
        Friend ReadOnly Property timer2() As String
            Get
                Return ResourceManager.GetString("timer2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 投票结束，
        '''获得通过
        '''未获通过
        '''赞成
        '''反对
        '''弃权
        '''没有国家行使否决权
        '''行使否决权
        '''投票已取消.
        '''</summary>
        Friend ReadOnly Property vote1() As String
            Get
                Return ResourceManager.GetString("vote1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Voting finished, 
        ''' Passed!!
        ''' Failed
        '''Yes
        '''No
        '''Abst.
        '''No nations perform veto power
        ''' perform veto power
        '''Voting cancelled.
        '''</summary>
        Friend ReadOnly Property vote2() As String
            Get
                Return ResourceManager.GetString("vote2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 发言结束，剩余时间让渡给
        '''发言结束，剩余时间让渡给问题
        '''提问的国家：
        '''发言结束，剩余时间让渡给评论
        '''评论的国家：
        '''发言结束，剩余时间让渡给主席
        '''发言结束，
        '''请问如何让渡？.
        '''</summary>
        Friend ReadOnly Property yield1() As String
            Get
                Return ResourceManager.GetString("yield1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Speech finished, time yield to 
        '''Speech finished, time yield to questions
        '''Questioner: 
        '''Speech finished, time yield to comments
        '''Commenter:
        '''Speech finished, time yield to chair
        '''Speech finished, 
        '''; how to yield the time?.
        '''</summary>
        Friend ReadOnly Property yield2() As String
            Get
                Return ResourceManager.GetString("yield2", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
